version: '3.8'

services:

  ms-eureka:
    build: ./ms-eureka
    ports:
      - "8761:8761"
    networks:
      - smartlogix-net
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  ms-auth:
    build: ./ms-auth
    ports:
      - "8081:8081"
    depends_on:
      ms-eureka:
        condition: service_healthy
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
    - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
    - SPRING_DATASOURCE_USERNAME=postgres.gkcyyzzaizzuglmyetpe
    - SPRING_DATASOURCE_PASSWORD=GkCMQaTgcoo4ETva
    - JWT_SECRET=smartlogix-secret-key-2024-super-segura-para-produccion-abc123
    networks:
      - smartlogix-net
    restart: always

  ms-clientes:
    build: ./ms-clientes
    ports:
      - "8082:8082"
    depends_on:
      ms-eureka:
        condition: service_healthy
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
    - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
    - SPRING_DATASOURCE_USERNAME=postgres.gkcyyzzaizzuglmyetpe
    - SPRING_DATASOURCE_PASSWORD=GkCMQaTgcoo4ETva
    - JWT_SECRET=smartlogix-secret-key-2024-super-segura-para-produccion-abc123
    networks:
      - smartlogix-net
    restart: always

  ms-inventario:
    build: ./ms-inventario
    ports:
      - "8083:8083"
    depends_on:
      ms-eureka:
        condition: service_healthy
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
    - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
    - SPRING_DATASOURCE_USERNAME=postgres.gkcyyzzaizzuglmyetpe
    - SPRING_DATASOURCE_PASSWORD=GkCMQaTgcoo4ETva
    - JWT_SECRET=smartlogix-secret-key-2024-super-segura-para-produccion-abc123
    networks:
      - smartlogix-net
    restart: always

  ms-pedidos:
    build: ./ms-pedidos
    ports:
      - "8084:8084"
    depends_on:
      ms-eureka:
        condition: service_healthy
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
    - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
    - SPRING_DATASOURCE_USERNAME=postgres.gkcyyzzaizzuglmyetpe
    - SPRING_DATASOURCE_PASSWORD=GkCMQaTgcoo4ETva
    - JWT_SECRET=smartlogix-secret-key-2024-super-segura-para-produccion-abc123
    networks:
      - smartlogix-net
    restart: always

  ms-gateway:
    build: ./ms-gateway
    ports:
      - "8080:8080"
    depends_on:
      ms-eureka:
        condition: service_healthy
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
    - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
    - SPRING_DATASOURCE_USERNAME=postgres.gkcyyzzaizzuglmyetpe
    - SPRING_DATASOURCE_PASSWORD=GkCMQaTgcoo4ETva
    - JWT_SECRET=smartlogix-secret-key-2024-super-segura-para-produccion-abc123
    networks:
      - smartlogix-net
    restart: always

networks:
  smartlogix-net:
    driver: bridge