name: CI/CD SmartLogix Backend

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build y Push imágenes Backend
      run: |
         SERVICES="ms-eureka ms-gateway ms-auth"
          for SERVICE in $SERVICES; do
            echo "Building $SERVICE..."
            cd $SERVICE
            chmod +x mvnw
            ./mvnw package -DskipTests -q
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE:latest .
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE:latest
            cd ..
          done

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Desplegar en EC2 App vía SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ms-eureka:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ms-gateway:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ms-auth:latest
          docker stop ms-eureka ms-gateway ms-auth || true
          docker rm ms-eureka ms-gateway ms-auth || true
           docker run -d --name ms-eureka -p 8761:8761 --restart always \
            ${{ secrets.DOCKERHUB_USERNAME }}/ms-eureka:latest
           docker run -d --name ms-gateway -p 8080:8080 --restart always \
            -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8761/eureka/ \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/ms-gateway:latest
            docker run -d --name ms-auth -p 8081:8081 --restart always \
            -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8761/eureka/ \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/ms-auth:latest

            